# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PAG.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QTextEdit, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(805, 789)
        Widget.setMaximumSize(QSize(805, 16777215))
        self.label_13 = QLabel(Widget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 458, 42, 16))
        self.textEdit_3 = QTextEdit(Widget)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.textEdit_3.setGeometry(QRect(10, 552, 781, 41))
        self.label_17 = QLabel(Widget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(500, 690, 189, 16))
        self.comboBox_3 = QComboBox(Widget)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(10, 160, 331, 22))
        self.lineEdit_2 = QLineEdit(Widget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(16, 712, 351, 22))
        self.label_7 = QLabel(Widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(6, 260, 166, 16))
        self.label_15 = QLabel(Widget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(16, 640, 127, 16))
        self.comboBox_6 = QComboBox(Widget)
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.comboBox_6.setGeometry(QRect(10, 352, 331, 22))
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 138, 56, 16))
        self.lineEdit_4 = QLineEdit(Widget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(500, 662, 271, 22))
        self.label_11 = QLabel(Widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 330, 110, 16))
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 88, 100, 16))
        self.comboBox = QComboBox(Widget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 60, 311, 22))
        self.lineEdit = QLineEdit(Widget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(40, 10, 133, 21))
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 188, 42, 16))
        self.textEdit_4 = QTextEdit(Widget)
        self.textEdit_4.setObjectName(u"textEdit_4")
        self.textEdit_4.setGeometry(QRect(490, 212, 256, 101))
        self.comboBox_7 = QComboBox(Widget)
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.comboBox_7.setGeometry(QRect(16, 662, 351, 22))
        self.comboBox_2 = QComboBox(Widget)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(10, 110, 331, 22))
        self.ButtonValide = QPushButton(Widget)
        self.ButtonValide.setObjectName(u"ButtonValide")
        self.ButtonValide.setGeometry(QRect(300, 750, 251, 24))
        self.label_8 = QLabel(Widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(6, 282, 168, 16))
        self.label_16 = QLabel(Widget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(16, 690, 100, 16))
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 27, 16))
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 38, 67, 16))
        self.textEdit_2 = QTextEdit(Widget)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(10, 480, 781, 41))
        self.comboBox_4 = QComboBox(Widget)
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(10, 210, 331, 22))
        self.lineEdit_3 = QLineEdit(Widget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(500, 712, 271, 22))
        self.textEdit = QTextEdit(Widget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(10, 412, 781, 41))
        self.label_12 = QLabel(Widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 390, 44, 16))
        self.label_14 = QLabel(Widget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 530, 89, 16))
        self.label_10 = QLabel(Widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(180, 282, 210, 16))
        self.label_18 = QLabel(Widget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(500, 640, 99, 16))
        self.label_9 = QLabel(Widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(180, 260, 210, 16))
        self.label_6 = QLabel(Widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(490, 190, 66, 16))

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Form", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"Mesure:", None))
        self.label_17.setText(QCoreApplication.translate("Widget", u"Evaluation de l'efficacit\u00e9 de l'action:", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"Responsable service du secteur:", None))
        self.label_15.setText(QCoreApplication.translate("Widget", u"Responsable de l'action:", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"R\u00e9dacteur:", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"Type (PA/PS/RQ/NC)", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"Origine de l'action:", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Widget", u"1", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Widget", u"2", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Widget", u"3", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("Widget", u"4", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("Widget", u"5", None))

        self.label_5.setText(QCoreApplication.translate("Widget", u"Secteur:", None))
        self.ButtonValide.setText(QCoreApplication.translate("Widget", u"Valider", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"Responsable activit\u00e9 du secteur:", None))
        self.label_16.setText(QCoreApplication.translate("Widget", u"Date de r\u00e9alisation:", None))
        self.label.setText(QCoreApplication.translate("Widget", u"Date:", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"Type d'audit:", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"Constat:", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"Commentaire(s):", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"------------------------------------------", None))
        self.label_18.setText(QCoreApplication.translate("Widget", u"D\u00e9lai de r\u00e9alisation", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"------------------------------------------", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"Ligne/Poste:", None))
    # retranslateUi

